cloud:
 aws:
  region:
   static: us-east-1
  stack:
   auto: false
  credentials:
   access-key: AKIAXECD3KXJPCGC2FRI
   secret-key: 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
logging:
  level:
    com:
     amazonaws:
      internal:
       InstanceMetadataServiceResourceFetcher: error
      util:
       EC2MetadataUtils: error
